/* Gera ESPECIFICACAO.md a partir de data.js + tipologia.js (node gerar-spec.js) */
const fs = require('fs');
const src = ['data.js', 'engine.js', 'tipologia.js', 'descricoes.js'].map((f) => fs.readFileSync(__dirname + '/' + f, 'utf8')).join('\n');
eval(
  src +
    '\n;Object.assign(globalThis,{ESCALA,PESOS,EIXOS,SUGESTOES,FAIXAS,TEMPERAMENTOS,EXPRESSOES,CALIBRAGENS,CALIBRAGEM_PILULA,TIPOS,siglaTemperamento,siglaExpressao,DESCRICOES,DESCRICOES_TEMPERAMENTO,DESCRICOES_EXPRESSAO});',
);

const esc = (s) => s.replace(/\|/g, '\\|');
const L = [];

L.push('# Sistema de perfil por dicotomias — especificação');
L.push('');
L.push(
  'Instrumento de 6 eixos dicotômicos, 7 afirmações por eixo (42 no total), escala forçada de 6 pontos, pesos por item, porcentagem por eixo e montagem de tipo psicológico sobre uma tabela de 16 assinaturas.',
);
L.push('');
L.push('## 1. Escala de resposta');
L.push('');
L.push('Seis bolinhas, sem centro: a pessoa é obrigada a escolher um lado.');
L.push('');
L.push('| Bolinha | Posição | Valor | r = valor ÷ 3 | Significado |');
L.push('| --- | --- | --- | --- | --- |');
ESCALA.forEach((o, i) => {
  L.push(`| ${o.id} | ${i + 1}ª ${o.lado === 'neg' ? '(esquerda)' : '(direita)'} | ${o.valor > 0 ? '+' : ''}${o.valor} | ${(o.valor / 3).toFixed(3).replace('.', ',')} | ${o.rotulo} |`);
});
L.push('');
L.push('## 2. Pesos por afirmação');
L.push('');
L.push('| Marcação | Peso | Critério de atribuição |');
L.push('| --- | --- | --- |');
L.push('| `mid` | 0,5 | Mede o eixo de forma indireta, é socialmente desejável, é condicional ("depende"), ou divide variância com outro eixo. |');
L.push('| `neutra` | 1,0 | Item válido e concreto, mas ancorado num contexto específico (escola, viagem, cozinha) ou com justificativa embutida que dá rota de fuga. |');
L.push('| `mor` | 1,5 | Descreve o comportamento-núcleo do polo, é observável e concordar com ele custa algo socialmente. Todo polo precisa de pelo menos um. |');
L.push('');
L.push('## 3. Cálculo do eixo');
L.push('');
L.push('Média ponderada **separada por polo**, não soma única. Isso corrige de uma vez o desbalanceamento de itens entre os lados e a aquiescência (a pessoa que concorda com tudo).');
L.push('');
L.push('\\[ M^{+} = \\frac{\\sum_{i \\in polo^{+}} w_i \\cdot r_i}{\\sum_{i \\in polo^{+}} w_i} \\qquad M^{-} = \\frac{\\sum_{i \\in polo^{-}} w_i \\cdot r_i}{\\sum_{i \\in polo^{-}} w_i} \\]');
L.push('');
L.push('\\[ X = \\frac{M^{+} - M^{-}}{2} \\quad \\in [-1,\\,+1] \\]');
L.push('');
L.push('\\[ \\%polo^{+} = \\frac{X + 1}{2} \\times 100 \\qquad \\%polo^{-} = 100 - \\%polo^{+} \\]');
L.push('');
L.push('Os dois polos sempre somam 100%.');
L.push('');
L.push('### Indicadores de qualidade');
L.push('');
L.push('- **Intensidade** = \\( |X| \\) — o quanto o perfil está definido naquele eixo.');
L.push('- **Aquiescência** = \\( (M^{+} + M^{-}) / 2 \\) — tendência a concordar (ou discordar) com tudo, independente de polo. Fora de ±0,45 o resultado deve ser considerado suspeito.');
L.push('');
L.push('| Intensidade | Faixa | Leitura |');
L.push('| --- | --- | --- |');
FAIXAS.forEach((f, i) => {
  const min = i === 0 ? '0' : FAIXAS[i - 1].max.toFixed(2).replace('.', ',');
  const max = f.max > 1 ? '1,00' : f.max.toFixed(2).replace('.', ',');
  L.push(`| ${min} – ${max} | ${f.rotulo} | ${f.nota} |`);
});
L.push('');
L.push('## 4. Calibragem item por item');
L.push('');
EIXOS.forEach((e) => {
  const p = e.itens.filter((i) => i.pole === 'pos').length;
  L.push(`### ${e.nome} — ${e.pos.code} / ${e.neg.code}`);
  L.push('');
  L.push(`${p} itens ${e.pos.code} contra ${e.itens.length - p} ${e.neg.code}.`);
  L.push('');
  L.push('| # | Polo | Peso | Afirmação | Por que este peso |');
  L.push('| --- | --- | --- | --- | --- |');
  e.itens.forEach((i, n) => {
    L.push(`| ${n + 1} | ${i.pole === 'pos' ? e.pos.code : e.neg.code} | \`${i.peso}\` | ${esc(i.texto)} | ${esc(i.nota)} |`);
  });
  L.push('');
});
L.push('## 5. Montagem do tipo psicológico');
L.push('');
L.push('A assinatura de 6 polos é comparada com as 16 linhas da tabela. Como 6 eixos binários geram 64 combinações e a tabela só cobre 16, a maioria das pessoas **não** bate 6 de 6 — o tipo sai da melhor aproximação.');
L.push('');
L.push('### Score de ajuste');
L.push('');
L.push('Para cada tipo candidato, soma-se ao longo dos 6 eixos:');
L.push('');
L.push('\\[ S = \\sum_{k=1}^{6} p_k \\cdot a_k \\qquad a_k = \\frac{\\%\\,no\\,polo\\,que\\,o\\,tipo\\,pede - 50}{50} \\]');
L.push('');
L.push('onde \\( p_k \\) é o peso de prioridade do eixo — **32, 16, 8, 4, 2, 1** na ordem de prioridade — e \\( a_k \\in [-1, +1] \\).');
L.push('');
L.push('Duas propriedades importantes desse desenho:');
L.push('');
L.push('1. **A prioridade é quase lexicográfica.** 32 > 16+8+4+2+1, então um eixo de prioridade alta vence a soma de todos os de baixo — desde que a pessoa esteja de fato definida nele.');
L.push('2. **O alinhamento é contínuo, não binário.** Um eixo em que a pessoa ficou 51/49 contribui com 0,02 × peso, praticamente nada. Um eixo indiferenciado não decide tipo, o que é o comportamento correto.');
L.push('');
L.push('Ajuste exibido = \\( (S / 63 + 1) / 2 \\times 100 \\), com 63 = soma dos pesos de prioridade.');
L.push('');
L.push('### As três calibragens');
L.push('');
L.push('O resultado não tem uma única leitura: a pílula acima do cartão do tipo permite trocar a hierarquia dos eixos, e o tipo é recalculado na hora. A explicação da leitura em uso aparece logo abaixo da pílula.');
L.push('');
L.push('| Calibragem | Hierarquia dos eixos |');
L.push('| --- | --- |');
CALIBRAGEM_PILULA.forEach((k) => {
  const c = CALIBRAGENS[k];
  L.push(`| **${c.nome}** | ${c.detalhe} |`);
});
L.push('');
L.push('A Calibragem Universal é a padrão e não usa uma hierarquia única: ela monta quatro listas independentes dos 16 tipos e depois as contrapõe.');
L.push('');
L.push('1. **Polos individuais** — cada eixo pesa a própria intensidade da resposta, sem ordem do modelo; é a leitura mais crua dos polos da pessoa.');
L.push('2. **Ordem universal** — pesos 32/16/8/4/2/1 aplicados na ordem ORIENTAÇÃO › INTERPRETAÇÃO › ORGANIZAÇÃO › COMUNICAÇÃO › ENFOQUE › POSTURA. Esta lista conta com peso dobrado na harmonização.');
L.push('3. **Leitura por temperamento** — a mesma lista da calibragem por temperamento.');
L.push('4. **Leitura por expressão** — a mesma lista da calibragem por expressão.');
L.push('');
L.push('Para cada tipo, cada lista fornece uma posição (de 1º a 16º) e uma compatibilidade. A nota de harmonia é a média ponderada de `0,5 × posição normalizada + 0,5 × compatibilidade` nas quatro listas (pesos 1, 2, 1, 1), menos `0,18 ×` a distância entre a melhor e a pior posição do tipo. O desconto elimina candidatos que aparecem muito bem em uma lista e muito mal em outra: vence quem harmoniza o conjunto, não quem lidera uma leitura isolada.');
L.push('A tela mostra as quatro listas, o primeiro colocado de cada uma e em que posição o tipo vencedor aparece nelas, além de quantas das quatro apontam o mesmo tipo — de 4 de 4 (tipo sólido por qualquer caminho) a 0 de 4 (vencedor de compromisso).');
L.push('');
L.push('### Expressões');
L.push('');
L.push('A expressão sai do cruzamento Orientação × Comunicação — o mesmo par de que a tabela deriva a Postura. Cada expressão reúne quatro tipos, um de cada temperamento:');
L.push('');
L.push('| Expressão | Polos | Tipos |');
L.push('| --- | --- | --- |');
Object.entries(EXPRESSOES).forEach(([sig, e]) => {
  const tps = TIPOS.filter((x) => siglaExpressao(x) === sig).map((x) => x.tipo).join(', ');
  L.push(`| ${e.nome} (${sig}) | ${e.orientacao} · ${e.postura} · ${e.comunicacao} | ${tps} |`);
});
L.push('');
L.push('### Temperamentos');
L.push('');
L.push('O temperamento sai do cruzamento Interpretação × Organização, e isso reproduz exatamente os quatro grupos da tabela:');
L.push('');
L.push('| Interpretação | Organização | Temperamento |');
L.push('| --- | --- | --- |');
[['MATERIALISTA', 'AFILIATIVO'], ['MATERIALISTA', 'PRAGMÁTICO'], ['IMATERIALISTA', 'AFILIATIVO'], ['IMATERIALISTA', 'PRAGMÁTICO']].forEach(([a, b]) => {
  const t = TEMPERAMENTOS[siglaTemperamento({ interpretacao: a, organizacao: b })];
  L.push(`| ${a} | ${b} | ${t.nome} (${t.sigla}) |`);
});
L.push('');
L.push('### Tabela dos 16 tipos');
L.push('');
L.push('| Tipo | Temp. | Orientação | Organização | Enfoque | Interpretação | Postura | Comunicação |');
L.push('| --- | --- | --- | --- | --- | --- | --- | --- |');
TIPOS.forEach((t) => {
  L.push(`| ${t.tipo} | ${t.temp} | ${t.orientacao} | ${t.organizacao} | ${t.enfoque} | ${t.interpretacao} | ${t.postura} | ${t.comunicacao} |`);
});
L.push('');
L.push('Tabela confirmada por você: **todos os oito tipos E são INICIADOR** e todos os oito tipos I são RESPONDEDOR. A variante literal que existia no protótipo (com ESTJ, ESFJ, ESTP e ESFP como RESPONDEDOR) foi removida do sistema.');
L.push('');
L.push('Verificações automáticas dessa tabela: as 16 assinaturas de seis polos são **únicas** (nenhum par de tipos tem a mesma combinação) e, alimentando o motor com um perfil puro de cada tipo (100% em cada polo que a linha pede), **todos os 16 resolvem para si mesmos** nas duas ordens de prioridade.');
L.push('');
L.push('## 6. Problemas estruturais encontrados');
L.push('');
L.push('### 6.1 A tabela tem 6 colunas, mas só 4 dimensões');
L.push('');
L.push('Conferindo as 16 linhas uma a uma, dois eixos nunca variam por conta própria:');
L.push('');
L.push('- **Enfoque = Organização × Interpretação.** SISTEMÁTICO aparece exatamente em MATERIALISTA+AFILIATIVO (Sentinelas) e IMATERIALISTA+PRAGMÁTICO (Teóricos); os outros dois cruzamentos dão INTERESSADO. Zero exceções nas 16 linhas — Enfoque é a segunda letra do temperamento, nada mais.');
L.push('- **Postura = Orientação × Comunicação.** MOVIMENTADO aparece exatamente em RESPONDEDOR+DIRECIONADO e INICIADOR+INFORMATIVO; os outros dois dão CONTROLADO. Zero exceções.');
L.push('');
L.push('As quatro dimensões que de fato distinguem os 16 tipos são **Orientação, Organização, Interpretação e Comunicação** — o mínimo necessário, já que \\( 2^4 = 16 \\).');
L.push('');
L.push('Consequências práticas:');
L.push('');
L.push('1. **14 das 42 afirmações não adicionam dimensão.** Elas medem de novo, por outro ângulo, o que os outros eixos já mediram. Isso não é desperdício se for intencional: vira teste de consistência. Quando Enfoque ou Postura contradizem o previsto, a resposta foi incoerente — e isso é informação de qualidade da aplicação, não de perfil.');
L.push('2. **A ordem de prioridade declarada põe um eixo derivado na frente de um independente.** Enfoque está em 3º e Comunicação em 6º, mas Comunicação é uma das 4 dimensões reais e Enfoque não é. Na ordem alternativa, os quatro independentes decidem primeiro e os dois derivados só desempatam.');
L.push('');
L.push('### 6.2 A primeira letra dos oito tipos extrovertidos — resolvido');
L.push('');
L.push('Na primeira versão da tabela, os quatro tipos E do bloco materialista (ESTJ, ESFJ, ESTP, ESFP) apareciam como RESPONDEDOR. Isso deixaria **nenhum tipo MATERIALISTA como INICIADOR** e, como Orientação é a prioridade número 1, empurraria toda pessoa iniciadora e materialista para um tipo imaterialista (N). Você confirmou E = INICIADOR nas oito linhas; o problema deixou de existir e a opção literal foi retirada do código.');
L.push('');
L.push('### 6.3 Itens que ainda merecem revisão');
L.push('');
const mids = EIXOS.flatMap((e) => e.itens.filter((i) => i.peso === 'mid').map((i) => ({ e, i })));
mids.forEach(({ e, i }) => {
  const corte = i.texto.length > 110 ? i.texto.slice(0, 110).replace(/[\s,;.]+\S*$/, '') + '…' : i.texto;
  L.push(`- **${e.nome}** (\`mid\`) — "${corte}" ${i.nota}`);
});
L.push('');
L.push('### 6.4 Redação');
L.push('');
L.push('- **Juízo de valor embutido.** "perder tempo planejando", "papinho de signo", "ideias burras", "jogo limpo", "sempre bem elogiados" — cada um empurra a resposta pela imagem social, não pelo traço. Trocar por termos simétricos.');
L.push('- **Uma ideia por afirmação.** Itens com três cláusulas encadeadas viram ruído: a pessoa concorda com uma parte e discorda de outra, e a bolinha escolhida não diz qual.');
L.push('- **Pares espelhados.** Os eixos mais confiáveis têm um item que afirma o polo A e outro que afirma exatamente o oposto. Quem responde as duas pontas no mesmo sentido revela inconsistência.');
L.push('');
L.push('## 7. Próximas trocas sugeridas');
L.push('');
L.push('| Eixo | Polo | Substituiria | Afirmação proposta | Motivo |');
L.push('| --- | --- | --- | --- | --- |');
SUGESTOES.forEach((s) => {
  L.push(`| ${EIXOS.find((e) => e.id === s.eixo).nome} | ${s.polo} | \`${s.substitui}\` | ${esc(s.texto)} | ${esc(s.razao)} |`);
});
L.push('');
L.push('## 8. Descrições dos 16 tipos');
L.push('');
L.push('Cada tipo tem um texto próprio construído **a partir dos seis polos da sua linha**, não de um retrato genérico: o parágrafo percorre os eixos na ordem de prioridade (Orientação → Organização → Enfoque → Interpretação → Postura → Comunicação) e fecha com o que a combinação produz. Cada tipo traz também um título curto, três apontamentos de *onde isso rende* e três de *onde isso custa*, mais a ilustração correspondente. O texto tem cerca de 110 palavras e fecha comparando o tipo aos outros quinze.');
L.push('');
L.push('| Tipo | Título | Assinatura de seis polos |');
L.push('| --- | --- | --- |');
TIPOS.forEach((t) => {
  const d = DESCRICOES[t.tipo];
  const polos = [t.orientacao, t.comunicacao, t.interpretacao, t.organizacao, t.enfoque, t.postura].join(' · ');
  L.push(`| ${t.tipo} | ${d ? esc(d.titulo) : '—'} | ${polos} |`);
});
L.push('');
L.push('Na interface isso aparece em três lugares: o retrato do tipo resultante ao fim do teste (ilustração + texto + rende/custa), a aba **Todos os tipos**, que lista as 16 descrições agrupadas por temperamento com o tipo da pessoa destacado, e os dois quadros logo abaixo do cartão do resultado — um de temperamento e um de expressão, cada um com cerca de 100 palavras em linguagem não técnica e as ilustrações dos quatro membros do grupo, em duas colunas de dois.');
L.push('');
L.push('| Temperamento | Cruzamento | Tipos |');
L.push('| --- | --- | --- |');
Object.entries(TEMPERAMENTOS).forEach(([sig, t]) => {
  const tps = TIPOS.filter((x) => x.temp === sig).map((x) => x.tipo).join(', ');
  L.push(`| ${t.nome} (${sig}) | ${esc(t.desc)} | ${tps} |`);
});
L.push('');
L.push('### Ornamentos');
L.push('');
L.push('Os braços ilustrados são a moldura gráfica do site. Cada temperamento tem quatro peças, desenhadas saindo da borda esquerda em direção ao centro; todas as outras direções são espelhamento e giro da mesma arte, feitos em CSS. Eles aparecem apenas nas quatro bordas da página — laterais, topo e base — e nunca saem de retângulos ou caixas de conteúdo. Durante a introdução e o teste os quatro temperamentos aparecem misturados e a moldura se remistura a cada troca de eixo. Ao chegar no resultado, todos os braços passam a ser do temperamento do tipo que saiu — inclusive no PDF, que traz seis peças por página em faixas fora da coluna de texto.');
L.push('');
L.push('Todo o conteúdo fica numa folha opaca que cobre o fundo e a moldura: os corpos de texto vivem nessa folha e os braços só aparecem em volta dela, nunca sobre a leitura.');
L.push('');
L.push('### Exportação em PDF');
L.push('');
L.push('O botão *Baixar meu resultado em PDF* gera um documento de 5 páginas, montado no navegador (jsPDF, sem servidor):');
L.push('');
L.push('1. **Capa** — sigla, temperamento, expressão, calibragem usada, título do tipo, ilustração, assinatura de seis polos, ajuste e margem sobre o segundo colocado, texto descritivo, rende/custa.');
L.push('2. **Seus dois grupos** — o texto de cerca de 100 palavras do temperamento e o da expressão, com os quatro membros de cada grupo.');
L.push('3. **Os seis eixos** — porcentagem dos dois polos, intensidade e o significado do polo dominante em cada eixo.');
L.push('4. **Como o tipo foi escolhido** — a resposta contra a linha da tabela, eixo por eixo na ordem de prioridade, mais as duas checagens de coerência.');
L.push('5. **Ranking e método** — os 16 tipos pelo ajuste e a explicação da escala, dos pesos e das fórmulas.');
L.push('');
L.push('## 9. Arquivos');
L.push('');
L.push('| Arquivo | Conteúdo |');
L.push('| --- | --- |');
L.push('| `data.js` | Escala, pesos, os 6 eixos com as 42 afirmações (polo, peso, justificativa) e as trocas sugeridas. |');
L.push('| `engine.js` | Motor de pontuação por eixo: médias por polo, X, porcentagens, intensidade, aquiescência. Sem dependência de interface. |');
L.push('| `tipologia.js` | Temperamentos, expressões, as três calibragens, tabela dos 16 tipos, score de ajuste, checagens de coerência. |');
L.push('| `descricoes.js` | Título, texto, três apontamentos de rende e três de custa dos 16 tipos, os textos dos 4 temperamentos e o caminho da ilustração de cada tipo. |');
L.push('| `app.js` | Interface: fluxo do teste, telas de resultado, retrato do tipo, galeria dos 16, aba de temperamento. |');
L.push('| `ornamentos.js` | Acervo de braços por temperamento e a moldura da página: posições, giros, espelhos e a mistura durante a navegação. |');
L.push('| `pdf.js` | Geração do PDF do resultado no próprio navegador, com a moldura de braços do temperamento. |');
L.push('| `index.html` | Marcação das três telas e das cinco abas de resultado. |');
L.push('| `img/*.jpg` | As 16 ilustrações de tipo. |');
L.push('| `img/orn/*.png` | As peças de ornamento, recortadas com fundo transparente. |');
L.push('| `styles.css` | Tokens de design, tema claro/escuro, escala de bolinhas, tabelas e ranking. |');
L.push('| `gerar-spec.js` | Gera este documento a partir dos dados, para não sair de sincronia. |');
L.push('');
L.push('---');
L.push('');
L.push(`Documento gerado a partir dos dados do sistema. ${EIXOS.length} eixos, ${EIXOS.reduce((a, e) => a + e.itens.length, 0)} afirmações, ${TIPOS.length} tipos.`);
L.push('');

fs.writeFileSync(__dirname + '/ESPECIFICACAO.md', L.join('\n'));
console.log('ESPECIFICACAO.md gerada:', L.length, 'linhas');
